Assignment2Project/Areas/Admin/Controllers/RolesManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Assignment2Project.Areas.Admin.Controllers
{
    [Authorize(Roles = "Estates_Admin")]
    [Area("Admin")]
    public class RolesManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RolesManagerController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            //Return a list of roles to the view.
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            //Create a new role from the string passed into the method.
            if(roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteRole(string id)
        {
            //Find the role by the id and remove it from the database.
            if(id != null)
            {
                var role = await _roleManager.FindByIdAsync(id);
                await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }
    }
}

Assignment2Project/Areas/Admin/Views/RolesManager/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    ViewData["Title"] = "Role Manager";
}
<h1>Roles Management</h1>

<form method="post" asp-action="AddRole" asp-controller="RolesManager">
    <div class="input-group">
        <input name="roleName" class="form-control w-25"/>
        <span class="input-group-btn">
            <button class="btn btn-info">Add New Role</button>
        </span>
    </div>
</form>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>ID</th>
            <th>Role</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var role in Model)
        {
            <tr>
                <td>@role.Id</td>
                <td>@role.Name</td>
                <td>
                    <a class="btn btn-danger" asp-action="DeleteRole" asp-route-id="@role.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>