Assignment2Project/Areas/Admin/Models/ManageInstitutionViewModel.cs
using Assignment2Project.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Assignment2Project.Areas.Admin.Models
{
    public class ManageInstitutionViewModel
    {
        public CustomUserModel User { get; set; }
        public IEnumerable<SelectListItem> InstitutionList { get; set; }
    }
}

Assignment2Project/Areas/Admin/Models/UserRolesViewModel.cs
using Assignment2Project.Models;

namespace Assignment2Project.Areas.Admin.Models
{
    public class UserRolesViewModel
    {
        public CustomUserModel User { get; set; }
        public List<string> Roles { get; set; }
        public InstitutionModel Institution { get; set; }
    }
}

Assignment2Project/Areas/Admin/Controllers/UserRolesController.cs
using Assignment2Project.Areas.Admin.Models;
using Assignment2Project.Data;
using Assignment2Project.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace Assignment2Project.Areas.Admin.Controllers
{
    [Authorize(Roles = "Estates_Admin")]
    [Area("Admin")]
    public class UserRolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<CustomUserModel> _userManager;
        private readonly ApplicationDbContext _db;
        public UserRolesController(RoleManager<IdentityRole> roleManager, UserManager<CustomUserModel> userManager, ApplicationDbContext db)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _db = db;
        }

        public async Task<IActionResult> Index(string q)
        {
            if(q != null)
            {
                //Creates a list of Users and an empty list of User roles view model.
                var users = await _userManager.Users.ToListAsync();
                var VMlist = new List<UserRolesViewModel>();
                //Loops through each user in the list
                foreach (var user in users)
                {
                    //Find the institution that is linked to the institution id of the user.
                    var institution = _db.Institutions.FirstOrDefault(i => i.Id == user.InstitutionId);
                    if (institution != null)
                    {
                        //Creates a user roles view model and then adds it to the list made earlier.
                        var currentVM = new UserRolesViewModel()
                        {
                            User = user,
                            Roles = new List<string>(await _userManager.GetRolesAsync(user)),
                            Institution = institution
                        };
                        VMlist.Add(currentVM);
                    }
                }
                //Returns the list of user roles view model to the view.
                var list = VMlist.Where(n =>n.User.UserName.ToLower().Contains(q.ToLower())).ToList();
                return View(list);
            }
            else
            {
                var users = await _userManager.Users.ToListAsync();
                var VMlist = new List<UserRolesViewModel>();

                foreach (var user in users)
                {
                    var institution = _db.Institutions.FirstOrDefault(i => i.Id == user.InstitutionId);
                    if (institution != null)
                    {
                        var currentVM = new UserRolesViewModel()
                        {
                            User = user,
                            Roles = new List<string>(await _userManager.GetRolesAsync(user)),
                            Institution = institution
                        };
                        VMlist.Add(currentVM);
                    }

                }
                return View(VMlist);
            }
         
        }

        //GET
        public async Task<IActionResult> Manage(string id)
        {
            //Finds the user that has the same id that is passed into the method.
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return RedirectToAction("Index");
            }
            //create a new list of manage user role view model.
            var viewModels = new List<ManageUserRoleViewModel>();
            //Loops through each role and assigns the value to a manage user role view model and then adds to the list
            //And finally returns the list to the view.
            foreach (var role in _roleManager.Roles)
            {
                var vm = new ManageUserRoleViewModel();
                vm.User = user;
                vm.Role = role;
                vm.IsInRole = await _userManager.IsInRoleAsync(user, role.Name);
                viewModels.Add(vm);
            }
            return View(viewModels);
        }

        //GET
        public async Task<IActionResult> ManageInstitution(string id)
        {
            //Find the user by the id, and creates a list of institutions from the database.
            var user = await _userManager.FindByIdAsync(id);
            var institution = await _db.Institutions.ToListAsync();
            if (user == null)
            {
                return RedirectToAction("Index");
            }
            //Creates a new view model that inputs the user and a select list of institutions to the view.
            ManageInstitutionViewModel viewModels = new ManageInstitutionViewModel()
            {
                User = user,
                InstitutionList = _db.Institutions.Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                })
            };

            return View(viewModels);
        }

        [HttpPost]
        public async Task<IActionResult> Manage(List<ManageUserRoleViewModel> model)
        {
            if (model != null && model.Count >= 1)
            {
                //Finds the user by the id.
                var user = await _userManager.FindByIdAsync(model[0].User.Id);
                if (user != null)
                {
                    //Finds the roles that is linked to the user and removes them from the roles.
                    var roles = await _userManager.GetRolesAsync(user);
                    var result = await _userManager.RemoveFromRolesAsync(user, roles);
                    if (!result.Succeeded)
                    {
                        ModelState.AddModelError("1", "Error Removing Roles.");
                        return View(model);
                    }
                    //Once the user has been removed from the roles, it now finds the new roles that have been selected and adds them to the user.
                    result = await _userManager.AddToRolesAsync(user, model.Where(x => x.IsInRole).Select(y => y.Role.Name));
                    if (!result.Succeeded)
                    {
                        ModelState.AddModelError("3", "Error Adding Roles.");
                        return View(model);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("2", "User Not Found.");
                    return View(model);
                }
            }
            else
            {
                return RedirectToAction("Manage");
            }
        }

        //Post function to update the institution for the user.
        [HttpPost]
        public async Task<IActionResult> ManageInstitution(ManageInstitutionViewModel model)
        {
            if (model != null)
            {
                //Finds the user from the model.
                var user = await _userManager.FindByIdAsync(model.User.Id);

                if (user != null)
                {
                    //Changes the institution Id to the new selected option.
                    user.InstitutionId = model.User.InstitutionId;
                    //Updates the database.
                    _db.Users.Update(user);
                    await _db.SaveChangesAsync();
                    return RedirectToAction("Manage");
                }
                else
                {
                    return RedirectToAction("Manage");
                }
            }
            return RedirectToAction("Manage");

        }
        public async Task<IActionResult> Delete(string id)
        {
            //Finds the user from the id and removes them from the database.
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return RedirectToAction("Index");
            }
            var roles = await _userManager.GetRolesAsync(user);
            await _userManager.RemoveFromRolesAsync(user, roles);
            await _userManager.DeleteAsync(user);
            return RedirectToAction("Index");
        }
    }
}

Assignment2Project/Areas/Admin/Views/UserRoles/Index.cshtml
@using Assignment2Project.Areas.Admin.Models
@model IEnumerable<UserRolesViewModel>

@{
    ViewData["Title"] = "User Manager";
}

<h1>User Roles Management</h1>

<form method="get" class="my-3">
    <div class="container-fluid">
        <div class="row">
            <div class="col mt-3">
                <p class="lh-1">Search by User:</p>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="search" id="q" name="q" value="@ViewData["q"]">
                    <button class="input-group-text" id="search" type="submit">Search</button>
                </div>
            </div>
        </div>
</form>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>User ID</th>
            <th>First Name</th>
            <th>Surname</th>
            <th>Roles</th>
            <th>Institution</th>
            <th>Manage Roles</th>
            <th>Manage Institution</th>

            <th>Manage Users</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.User.Id</td>
                <td>@user.User.Fname</td>
                <td>@user.User.Sname</td>
                <td>@string.Join(" , ", user.Roles.ToList())</td>
                <td>@user.Institution.Name</td>
                <td>
                    <a class="btn btn-info" asp-controller="UserRoles" asp-action="Manage" asp-route-id="@user.User.Id">Manage Roles</a>
                </td>
                <td>
                    <a class="btn btn-info" asp-controller="UserRoles" asp-action="ManageInstitution" asp-route-id="@user.User.Id">Manage Institution</a>
                </td>
                <td>
                    <a class="btn btn-danger" asp-controller="UserRoles" asp-action="Delete" asp-route-id="@user.User.Id">Delete User</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Assignment2Project/Areas/Admin/Views/UserRoles/Manage.cshtml
@using Assignment2Project.Areas.Admin.Models
@model List<ManageUserRoleViewModel>
@{
    ViewData["Title"] = "Manage";
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Manage @Model.FirstOrDefault().User.Fname 's Roles</h2>
        </div>
        <div class="card-body">
            @for (int i=0; i < Model.Count; i++)
            {
                <div class="form-check">
                    <input type="hidden" asp-for="@Model[i].User.Id"/>
                    <input type="hidden" asp-for="@Model[i].Role.Name"/>
                    <input class="form-check-input" type="checkbox" asp-for="@Model[i].IsInRole"/>
                    <label class="form-check-label">
                        @Model[i].Role.Name
                    </label>
                </div>
            }
        </div>
        <div class="card-footer">
            <button class="btn btn-info" type="submit">Update</button>
            <a class="btn btn-danger" asp-action="Index">Cancel</a>
        </div>
    </div>
</form>

Assignment2Project/Areas/Admin/Views/UserRoles/ManageInstitution.cshtml
@using Assignment2Project.Areas.Admin.Models
@model ManageInstitutionViewModel
@{
    ViewData["Title"] = "ManageInstitution";
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Manage @Model.User.Fname 's Institution</h2>
        </div>
        <div class="card-body">
            <h5>Select User's Institution:</h5>

              <input type="hidden" asp-for="@Model.User.Id"/>

              @Html.DropDownListFor(m => m.User.InstitutionId, Model.InstitutionList, "Select a institution", new {@class = "form-select"})

              <span asp-validation-for="User.InstitutionId" class="text-danger"></span>

        </div>
        <div class="card-footer">
            <button class="btn btn-info" type="submit">Update</button>
            <a class="btn btn-danger" asp-action="Index">Cancel</a>
        </div>
    </div>
</form>