Assignment2Project/Models/GeneralIssueViewModel.cs
namespace Assignment2Project.Models
{
    public class GeneralIssueViewModel
    {
        public CustomUserModel User { get; set; }
        public GeneralIssueModel GeneralIssue { get; set; }
    }
}

Assignment2Project/Models/HomeViewModel.cs
namespace Assignment2Project.Models
{
    public class HomeViewModel
    {
        public List<AssetModel> Assets { get; set; }
        public List<RoomModel> Rooms { get; set; }
        public List<MaintenanceIssueModel> MaintenanceIssues { get; set; }
        public List<GeneralIssueModel> GeneralIssues { get; set; }
    }
}

Assignment2Project/Controllers/GeneralIssueController.cs
using Assignment2Project.Data;
using Assignment2Project.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Assignment2Project.Controllers
{
    public class GeneralIssueController : Controller
    {
        public readonly ApplicationDbContext _db;
        public readonly UserManager<CustomUserModel> _userManager;

        public GeneralIssueController(ApplicationDbContext db, UserManager<CustomUserModel> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Institution_Manager")]

        public IActionResult Create()
        {
            //Passes an empty general issue model into the create view.
            GeneralIssueModel model = new GeneralIssueModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(GeneralIssueModel model)
        {
            //Returns the data needed to create a general issue from the create view.
            var loggedIn = await _userManager.GetUserAsync(User);

            if (model != null)
            {
                GeneralIssueModel issueModel = new GeneralIssueModel();
                issueModel.DateRaised = DateTime.Now;
                issueModel.UserId = loggedIn.Id;
                issueModel.Details = model.Details;
                issueModel.IsResolved = false;
                issueModel.InstitutionId = loggedIn.InstitutionId;
                await _db.GeneralIssues.AddAsync(issueModel);
                await _db.SaveChangesAsync();
                //Redirects to the Issues action in the Home controller.
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Institution_Manager")]

        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return RedirectToAction("GeneralIssues", "Home");
            }
            var issue = await _db.GeneralIssues.Where(x => x.Id == id).FirstOrDefaultAsync();
            issue.GeneralComments = await _db.GeneralComments.Where(x => x.GeneralIssueId == issue.Id).Include("User").OrderByDescending(x => x.TimeStamp).ToListAsync();
            if (issue == null)
            {
                return RedirectToAction("GeneralIssues", "Home");
            }
            var VM = new GeneralIssueViewModel();

            //Creates a list to populate with IssueViewModels
            //Loops through both the list of maintenance issues and general 
            var user = _db.Users.FirstOrDefault(i => i.Id == issue.UserId);
            if (user != null)
            {
                GeneralIssueViewModel issueVM = new GeneralIssueViewModel()
                {
                    User = user,
                    GeneralIssue = issue
                };
                VM = issueVM;
            }

            return View(VM);
        }


        [HttpPost]
        public async Task<IActionResult> AddComment(string comment, int id)
        {
            //Finds the issue from the database where the id is the same and then adds a comment to the list of comments in the model.
            var issue = await _db.GeneralIssues.Where(x => x.Id == id).FirstOrDefaultAsync();
            issue.GeneralComments.Add(new GeneralCommentModel
            {
                Comment = comment,
                GeneralIssueId = id,
                TimeStamp = DateTime.Now,
                User = await _userManager.FindByEmailAsync(User.Identity.Name)
            });
            _db.GeneralIssues.Update(issue);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Details), new { id = issue.Id });
        }

        [Authorize(Roles = "Institution_Manager")]

        public async Task<IActionResult> Resolution(int id)
        {
            if (id == null)
            {
                return RedirectToAction("GeneralIssues", "Home");
            }
            //Finds the correct issue from the database using the id.
            var issue = await _db.GeneralIssues.Where(x => x.Id == id).FirstOrDefaultAsync();

            if (issue == null)
            {
                return RedirectToAction("GeneralIssues", "Home");
            }
            //Creates a new view model and adds the issue and a new resolution model.
            GeneralResolutionViewModel resVM = new GeneralResolutionViewModel()
            {
                GeneralIssue = issue,
                Resolution = new ResolutionModel()
            };
            //Returns the view model.
            return View(resVM);
        }

        [HttpPost]
        public async Task<IActionResult> AddResolution(string details, int id)
        {
            //finds the issue from the database using the id.
            var issue = await _db.GeneralIssues.Where(n => n.Id == id).FirstOrDefaultAsync();
            //Adds a resolution comment to the issue that was found and updates it in the database.
            issue.ResolutionComments.Add(new GeneralResolutionModel
            {
                GeneralIssueId = id,
                DateResolved = DateTime.Now,
                User = await _userManager.FindByEmailAsync(User.Identity.Name),
                Details = details
            });

            issue.IsResolved = true;
            _db.GeneralIssues.Update(issue);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Resolution), new { id = issue.Id });
        }

        [Authorize(Roles = "Institution_Staff")]

        public IActionResult CreateStaff()
        {
            //Passes an empty general issue model into the create view.
            GeneralIssueModel model = new GeneralIssueModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateStaff(GeneralIssueModel model)
        {
            //Returns the data needed to create a general issue from the create view.
            var loggedIn = await _userManager.GetUserAsync(User);

            if (model != null)
            {
                GeneralIssueModel issueModel = new GeneralIssueModel();
                issueModel.DateRaised = DateTime.Now;
                issueModel.UserId = loggedIn.Id;
                issueModel.Details = model.Details;
                issueModel.IsResolved = false;
                issueModel.InstitutionId = loggedIn.InstitutionId;
                await _db.GeneralIssues.AddAsync(issueModel);
                await _db.SaveChangesAsync();
                //Redirects to the Issues action in the Home controller.
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Institution_Manager")]
        public async Task<IActionResult> DetailsStaff(int id)
        {
            if (id == null)
            {
                return RedirectToAction("GeneralIssues", "Home");
            }
            var issue = await _db.GeneralIssues.Where(x => x.Id == id).FirstOrDefaultAsync();
            issue.GeneralComments = await _db.GeneralComments.Where(x => x.GeneralIssueId == issue.Id).Include("User").OrderByDescending(x => x.TimeStamp).ToListAsync();
            if (issue == null)
            {
                return RedirectToAction("GeneralIssues", "Home");
            }
            var VM = new GeneralIssueViewModel();

            //Creates a list to populate with IssueViewModels
            //Loops through both the list of maintenance issues and general 
            var user = _db.Users.FirstOrDefault(i => i.Id == issue.UserId);
            if (user != null)
            {
                GeneralIssueViewModel issueVM = new GeneralIssueViewModel()
                {
                    User = user,
                    GeneralIssue = issue
                };
                VM = issueVM;
            }
            return View(VM);
        }
    }
}

Assignment2Project/Views/Home/GeneralIssues.cshtml
@model IEnumerable<GeneralIssueViewModel>
@{
    ViewData["Title"] = "Issues Page";
}
<a asp-controller="GeneralIssue" asp-action="Create" class="btn btn-info mb-3">Create New Issue</a>

<form method="get" class="my-3">
    <div class="container-fluid">
        <div class="row">
            <div class="col mt-3">
                <p class="lh-1">Search by User:</p>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="search" id="q" name="q" value="@ViewData["q"]">
                    <button class="input-group-text" id="search" type="submit">Search</button>
                </div>
            </div>           
        </div>
</form>
<div class="col">
    <div class="card shadow card-bg p-2">
        <div class="card-body">
            <h3 class="mb-3 card-text">Open General Issues:</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th class="card-text">Logged By</th>
                        <th class="card-text">Time Raised</th>
                        <th class="card-text">Resolved?</th>
                        <th class="card-text">Manage</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var issue in Model)
                    {
                        <tr>
                            <td class="card-text">@issue.User.UserName</td>
                            <td class="card-text">@issue.GeneralIssue.DateRaised</td>
                            <td class="card-text">@(issue.GeneralIssue.IsResolved ? "Yes" : "No")</td>
                            <td>
                                <a asp-controller="GeneralIssue" asp-action="Details" asp-route-id="@issue.GeneralIssue.Id" class="btn btn-info">Details</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Assignment2Project/Views/Home/GeneralIssuesStaff.cshtml
@model IEnumerable<GeneralIssueViewModel>
@{
    ViewData["Title"] = "Issues Page";
}
<a asp-controller="GeneralIssue" asp-action="CreateStaff" class="btn btn-info mb-3">Create New Issue</a>

<form method="get" class="my-3">
    <div class="container-fluid">
        <div class="row">
            <div class="col mt-3">
                <p class="lh-1">Search by your username to find your closed tickets:</p>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="search" id="q" name="q" value="@ViewData["q"]">
                    <button class="input-group-text" id="search" type="submit">Search</button>
                </div>
            </div>           
        </div>
</form>
<div class="col">
    <div class="card shadow card-bg p-2">
        <div class="card-body">
            <h3 class="mb-3 card-text">Open General Issues:</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th class="card-text">Logged By</th>
                        <th class="card-text">Time Raised</th>
                        <th class="card-text">Resolved?</th>
                        <th class="card-text">Manage</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var issue in Model)
                    {
                        <tr>
                            <td class="card-text">@issue.User.UserName</td>
                            <td class="card-text">@issue.GeneralIssue.DateRaised</td>
                            <td class="card-text">@(issue.GeneralIssue.IsResolved ? "Yes" : "No")</td>
                            <td>
                                <a asp-controller="GeneralIssue" asp-action="DetailsStaff" asp-route-id="@issue.GeneralIssue.Id" class="btn btn-info">Details</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Assignment2Project/Views/Home/Index.cshtml
@model HomeViewModel;
@{
    ViewData["Title"] = "Home Page";
}

<div class="my-5">
    <a asp-controller="MaintenanceIssue" asp-action="CreateStaff" class="btn btn-info me-3 fs-4">Submit a Maintenance Issue</a>
    <a asp-controller="GeneralIssue" asp-action="CreateStaff" class="btn btn-info ms-5 fs-4">Submit a General Issue</a>
</div>
<div class="my-2">
    <h4 class="header-text">Use the appropriate dropdown in the navigation bar to find more tools.</h4>
</div>

<div class="row mt-2">
    <div class="col">
        <div class="card shadow p-3">
            <div class="card-header">
                <h3 class="header-text">Rooms in Institution:</h3>
            </div>
            <table class="table table-striped mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Category</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var room in Model.Rooms)
                    {
                        <tr>
                            <td>@room.Id</td>
                            <td>@room.Name</td>
                            <td>@room.Category.Name</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="col">
        <div class="card shadow p-3">
            <div class="card-header">
                <h3 class="header-text">Assets in Institution:</h3>
            </div>
            <table class="table table-striped mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Room</th>
                        <th>Category</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var asset in Model.Assets)
                    {
                        <tr>
                            <td>@asset.Id</td>
                            <td>@asset.Name</td>
                            <td>@asset.Room.Name</td>
                            <td>@asset.Category.Name</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row mt-5">
    <div class="col">
        <div class="card shadow p-3">
            <div class="card-header">
                <h3 class="header-text">Your Current Unresolved Maintenance Issues:</h3>
            </div>
            <table class="table table-striped mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Date Logged</th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var asset in Model.MaintenanceIssues)
                    {
                        <tr>
                            <td>@asset.Id</td>
                            <td>@asset.TimeRaised</td>
                            <td>@asset.Details</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row mt-5">
    <div class="col">
        <div class="card shadow p-3">
            <div class="card-header">
                <h3 class="header-text">Your Current Unresolved General Issues:</h3>
            </div>
            <table class="table table-striped mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Date Logged</th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var asset in Model.GeneralIssues)
                    {
                        <tr>
                            <td>@asset.Id</td>
                            <td>@asset.DateRaised</td>
                            <td>@asset.Details</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Assignment2Project/Views/Home/MaintenanceIssues.cshtml
@model IEnumerable<IssueViewModel>
@{
    ViewData["Title"] = "Issues Page";
}
<form method="get" class="my-3">
    <div class="container-fluid">
        <div class="row">
            <div class="col mt-3">
                <p class="lh-1">Search by User:</p>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="search" id="q" name="q" value="@ViewData["q"]">
                    <button class="input-group-text" id="search" type="submit">Search</button>
                </div>
            </div>           
        </div>
</form>
<div class="col">
    <div class="card shadow card-bg p-2">
        <div class="card-body">
            <h3 class="mb-3 card-text">Open Maintenance Issues:</h3>

            <table class="table">
                <thead>
                    <tr>
                        <th class="card-text">Logged By</th>
                        <th class="card-text">Room</th>
                        <th class="card-text">Assets</th>
                        <th class="card-text">Time Raised</th>
                        <th class="card-text">Resolved?</th>
                        <th class="card-text">Manage</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var issue in Model)
                    {
                        <tr>
                            <td class="card-text">@issue.User.UserName</td>
                            <td class="card-text">@issue.Room.Name</td>
                            <td class="card-text">@issue.Asset.Name</td>
                            <td class="card-text">@issue.MaintenanceIssues.TimeRaised</td>
                            <td class="card-text">@(issue.MaintenanceIssues.IsResolved ? "Yes" : "No")</td>
                            <td>
                                <a asp-controller="MaintenanceIssue" asp-action="Details" asp-route-id="@issue.MaintenanceIssues.Id" class="btn btn-info">Details</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Assignment2Project/Views/Home/MaintenanceIssuesStaff.cshtml
@model IEnumerable<IssueViewModel>
@{
    ViewData["Title"] = "Issues Page";
}
<a asp-controller="MaintenanceIssue" asp-action="CreateStaff" class="btn btn-info mb-3">Create New Issue</a>

<form method="get" class="my-3">
    <div class="container-fluid">
        <div class="row">
            <div class="col mt-3">
                <p class="lh-1">Search by your username to find your closed tickets:</p>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="search" id="q" name="q" value="@ViewData["q"]">
                    <button class="input-group-text" id="search" type="submit">Search</button>
                </div>
            </div>           
        </div>
</form>
<div class="col">
    <div class="card shadow card-bg p-2">
        <div class="card-body">
            <h3 class="mb-3 card-text">Open Maintenance Issues:</h3>

            <table class="table">
                <thead>
                    <tr>
                        <th class="card-text">Logged By</th>
                        <th class="card-text">Room</th>
                        <th class="card-text">Assets</th>
                        <th class="card-text">Time Raised</th>
                        <th class="card-text">Resolved?</th>
                        <th class="card-text">Manage</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var issue in Model)
                    {
                        <tr>
                            <td class="card-text">@issue.User.UserName</td>
                            <td class="card-text">@issue.Room.Name</td>
                            <td class="card-text">@issue.Asset.Name</td>
                            <td class="card-text">@issue.MaintenanceIssues.TimeRaised</td>
                            <td class="card-text">@(issue.MaintenanceIssues.IsResolved ? "Yes" : "No")</td>
                            <td>
                                <a asp-controller="MaintenanceIssue" asp-action="DetailsStaff" asp-route-id="@issue.MaintenanceIssues.Id" class="btn btn-info">Details</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>